port: 5000
db:
  url: mongodb://root:password@localhost:27017/protocolServer?authSource=admin
app:
  mode: bap

  actions:
    - search
    - init

  privateKey: "NNu7GET375vsnrtsxjW6mCzJFnEUuYTYv5avpao1wz4aIXFc7BvXucdnxsLPfUmPqkH2+IY8UZSUMDEH+3Odrw=="
  publicKey: "GiFxXOwb17nHZ8bCz31Jj6pB9viGPFGUlDAxB/tzna8="

  subscriberId: "dev.bap.protocol-server.com"
  subscriberUri: "https://ayush.free.beeceptor.com/"
  
  registryUrl: https://registry.becknprotocol.io/subscribers
  auth: true
  uniqueKey: "dev.bap.protocol-server.key"
  
  city: "std:080"
  country: "IND"

  ttl: "P1M"
  lookupCacheTTL: "PT10S"

  httpTimeout: 3000
  httpRetryCount: 2
  
  clientUrl: "https://beckn.free.beeceptor.com/clientURL"